apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xfntests.demo.upbound.io
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: demo.upbound.io/v1alpha1
    kind: XFnTest
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            region: us-west-2
      name: s3bucket
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
  functions:
    - name: fn-test
      type: Container
      container:
        image: us-west2-docker.pkg.dev/crossplane-playground/garreeoke-up/fn-test:v1